PUT http://localhost:3003/api/blogs/5ef5f3e88ff7ea488425e054
Content-Type: application/json

{
    "title":"Java Full Stack Web",
    "author":"Kibrom",
    "url":"https://javadevpostblog.org/",
    "likes":1500
}